I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 105, in script
    with zoomOut
  File "game/script.rpy", line 105, in <module>
    with zoomOut
NameError: name 'zoomOut' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 105, in script
    with zoomOut
  File "D:\Jogos\Ren'Py\renpy-7.3.5-sdk\renpy\ast.py", line 1382, in execute
    trans = renpy.python.py_eval(self.expr)
  File "D:\Jogos\Ren'Py\renpy-7.3.5-sdk\renpy\python.py", line 2059, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "D:\Jogos\Ren'Py\renpy-7.3.5-sdk\renpy\python.py", line 2052, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 105, in <module>
    with zoomOut
NameError: name 'zoomOut' is not defined

Windows-8-6.2.9200
Ren'Py 7.3.5.606
SIFavela 1.0
Sun Mar 01 20:14:16 2020
