I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 171, in script
    show iKot at posAtvR
  File "game/script.rpy", line 171, in <module>
    show iKot at posAtvR
NameError: name 'posAtvR' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 171, in script
    show iKot at posAtvR
  File "D:\Jogos\Ren'Py\renpy-7.3.5-sdk\renpy\ast.py", line 1183, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "D:\Jogos\Ren'Py\renpy-7.3.5-sdk\renpy\ast.py", line 1142, in show_imspec
    at_list = [ renpy.python.py_eval(i) for i in at_list ]
  File "D:\Jogos\Ren'Py\renpy-7.3.5-sdk\renpy\python.py", line 2059, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "D:\Jogos\Ren'Py\renpy-7.3.5-sdk\renpy\python.py", line 2052, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 171, in <module>
    show iKot at posAtvR
NameError: name 'posAtvR' is not defined

Windows-8-6.2.9200
Ren'Py 7.3.5.606
SIFavela 1.0
Mon Mar 02 00:11:37 2020
